language: php
php:
- 7.1
- 7.2
- 7.3
env:
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
before_script:
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
- wget https://scrutinizer-ci.com/ocular.phar
after_script:
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
